### ISSUE TITLE
Archive old vacancies

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/jobs-app#8]
We need a managerial functionality to archive old jobs (closed vacancies).

Ideally manager can 
- choose which jobs are archival
- archive them via select functionality
- archive multiple of them within one action
- Archive could be available to public (can be used later for a market stats purpose: compare jobs in 2023 with 2024 etc)

Maybe archival action should do PR here - not sure how to do moderation part, so not everyone could archive jobs without our moderation & approval action.

Future state: org representative should archive their jobs without us micro-managing them, but only merging PRs or approving at the front-end.

**Comment by Barabazs** [comment]
Without diving too deep into this, I think you would need this for the frontend:
* a database to store who is an admin
* Sign-In with Ethereum (not like the current "connect wallet" button)

> Maybe archival action should do PR here

Doing it with a PR would require implementing weird workarounds since the data does not live in the repo, but in an external database.

> Future state: org representative should archive their jobs without us micro-managing them, but only merging PRs or approving at the front-end.

I think this could be achieved by using SIWE and just do a DB lookup to display the entries created by the logged in user.

**Comment by Barabazs** [comment]
> - a database to store who is an admin
> - Sign In with Ethereum (not like the current "connect wallet" button)

This would require proper scoping, but I'm afraid it would exceed my current bandwidth.

**Comment by Msiusko** [comment]
Hard to scope here from my side, because I don't know how to do it.
Because, basically what we can do - just create a separate category like "Archive" & make a new functionality "/archive" where there's 
- list of all jobs
- checklist (ability to "mark" every job one by one)
- and a button at the end "archive"

Functionality will move job from the general list to Archive "page". 

What do you think?

**Comment by Barabazs** [comment]
> Hard to scope here from my side, because I don't know how to do it. Because, basically what we can do - just create a separate category like "Archive" & make a new functionality "/archive" where there's
> 
>     * list of all jobs
> 
>     * checklist (ability to "mark" every job one by one)
> 
>     * and a button at the end "archive"
> 
> 
> Functionality will move job from the general list to Archive "page".
> 
> What do you think?

Just making that page and functionality is relatively straightforward. The hard part (at least for me) is setting up proper authentication with SIWE and Astro. I've done some more research and couldn't find resources on how to do combine both. And since I'm not a frontend dev, it's not something I can do in a reasonable amount of time.

**Comment by Barabazs** [comment]
I gave it a few more shots, but I can't get a proper SIWE/Astro implementation working. There are also no docs to implement this, so I would suggest migrating this project to Next.js first and then implement SIWE for the admin functions.

**Comment by Barabazs** [comment]
I'm going to close this and reopen a new new issue with the open points.

Completed with PR #19
* archive one or more jobs in one action
* archive page for admins (protected with SIWE & database)
